SINGLE_MULTICORE_BATCHES = {'CombineFiles',
                            'SearchPreparation',
                            'CombineFiles',
                            'ErrorCorrection',
                            'FdrFilter',
                            'SecpepCombineFiles',
                            'FdrFilterSp',
                            'RtAlign',
                            'MatchBetweenRunsWorker',
                            'LibraryFileMatch',
                            'PrepareProteinAssembly',
                            'FinishProteinAssembly',
                            'DependentPeptideHistogram',
                            'DependentPeptidePep',
                            'DependentPeptideApplyFdr',
                            'DependentCalculator',
                            'LfqNorm',
                            'LfqCollect'}